# K-means
https://scikit-learn.org/stable/
<img src="https://mofanpy.com/static/results/sklearn/2_1_1.png">

## K-means是一種分群方法，為非監督式學習

### 1. 設定n群
### 2. K-means隨機給予n個群心
### 3. 每個點用距離公式計算並分類給最近的群
### 4. 用每一群的點重新計算群心
### 5. 重複3、4步驟直到收斂

In [1]:
# %matplotlib inline

# import random
# import numpy as np
# from sklearn import cluster, metrics
# import matplotlib.pyplot as plt

# feature = np.array([2, 2])
# for i in range(3000):
#     if i%3 == 0:
#         x = 3 + random.normalvariate(0, 1.2)
#         y = 3 + random.normalvariate(0, 1.2)
#         feature = np.vstack((feature, [x, y]))
#         plt.scatter(x, y , color='b', s=2)
#     elif i%3 == 1:
#         x = 7 + random.normalvariate(0, 1)
#         y = 7 + random.normalvariate(0, 1)
#         feature = np.vstack((feature, [x, y]))
#         plt.scatter(x, y , color='r', s=2)
#     else:
#         x = 8 + random.normalvariate(0, 0.7)
#         y = 2 + random.normalvariate(0, 0.7)
#         feature = np.vstack((feature, [x, y]))
#         plt.scatter(x, y , color='g', s=2)
# feature = feature[1:]

# plt.xlim(0, 10)
# plt.ylim(0, 10)
# plt.show()

In [2]:
# feature

### K-means官方文件
https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

In [3]:
# # 迴圈
# silhouette_avgs = []
# ks = range(2, 7)
# for k in ks:
#     kmeans_fit = cluster.KMeans(n_clusters = k).fit(feature)
#     cluster_labels = kmeans_fit.labels_
#     silhouette_avg = metrics.silhouette_score(feature, cluster_labels) # -1 ~ 1
#     silhouette_avgs.append(silhouette_avg)

# # 作圖並印出 k = 2 到 10 的績效
# plt.bar(ks, silhouette_avgs)
# plt.show()
# print(silhouette_avgs)

In [4]:
# print(cluster_labels)

In [5]:
# from IPython.display import HTML
# HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/0DGtyMBOZ-c" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>')
# # 出處: https://chih-sheng-huang821.medium.com/%E6%A9%9F%E5%99%A8%E5%AD%B8%E7%BF%92-%E9%9B%86%E7%BE%A4%E5%88%86%E6%9E%90-k-means-clustering-e608a7fe1b43

# KNN(k nearest neighbors)
## KNN可以做分類或回歸，為監督式學習
### 1. 設定k值
### 2. 計算距離公式找出k個最相近的特徵
### 3. 分類: k個特徵投票、回歸: 平均k個特徵
<img src="https://ww2.mathworks.cn/matlabcentral/mlc-downloads/downloads/03faee64-e85e-4ea0-a2b4-e5964949e2d1/d99b9a4d-618c-45f0-86d1-388bdf852c1d/images/screenshot.gif">

### 蒐集資料
python MLGame.py -i ml_play_template.py -f 200 -r arkanoid NORMAL 3

In [6]:
import pickle
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import  classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedShuffleSplit

#試取資料
file = open("..\log\ml_2021-06-09_14-58-15.pickle", "rb")
data = pickle.load(file)
file.close()

print(data)

{'record_format_version': 2, 'ml': {'scene_info': [{'frame': 0, 'status': 'GAME_ALIVE', 'snake_head': (40, 40), 'snake_body': [(40, 30), (40, 20), (40, 10)], 'food': (290, 280)}, {'frame': 1, 'status': 'GAME_ALIVE', 'snake_head': (50, 40), 'snake_body': [(40, 40), (40, 30), (40, 20)], 'food': (290, 280)}, {'frame': 2, 'status': 'GAME_ALIVE', 'snake_head': (50, 50), 'snake_body': [(50, 40), (40, 40), (40, 30)], 'food': (290, 280)}, {'frame': 3, 'status': 'GAME_ALIVE', 'snake_head': (60, 50), 'snake_body': [(50, 50), (50, 40), (40, 40)], 'food': (290, 280)}, {'frame': 4, 'status': 'GAME_ALIVE', 'snake_head': (60, 60), 'snake_body': [(60, 50), (50, 50), (50, 40)], 'food': (290, 280)}, {'frame': 5, 'status': 'GAME_ALIVE', 'snake_head': (70, 60), 'snake_body': [(60, 60), (60, 50), (50, 50)], 'food': (290, 280)}, {'frame': 6, 'status': 'GAME_ALIVE', 'snake_head': (70, 70), 'snake_body': [(70, 60), (60, 60), (60, 50)], 'food': (290, 280)}, {'frame': 7, 'status': 'GAME_ALIVE', 'snake_head': (8

In [7]:
game_info = data['ml']['scene_info']
game_command = data['ml']['command']
game_info = []
game_command = []
print(game_info)
print(game_command)

[]
[]


In [8]:
import os
dir_path = "..\log"
for file_path in os.listdir(dir_path):
    #print(file_path)
    with open('..\\log\\' + file_path , 'rb') as f:
        data = pickle.load(f)
        #print(data)
        #print("-------------------")
    game_info = game_info + data['ml']['scene_info']
    game_command = game_command + data['ml']['command']
    #game_2P_command = game_2P_command + data['ml_2P']['command']
    #file.close()
# for i in range(2, 4):
#     path = "../log/n3 (" + str(i) + ").pickle"
#     file = open(path, "rb")
#     data = pickle.load(file)
#     game_info = game_info + data['scene_info']
#     game_command = game_command + data['command']
#     file.close()
    
print('game0 ')
print(game_info[0])
print(len(game_command))
print(len(game_info))

game0 
{'frame': 0, 'status': 'GAME_ALIVE', 'snake_head': (40, 40), 'snake_body': [(40, 30), (40, 20), (40, 10)], 'food': (200, 150)}
656994
656994


### 特徵整理

In [9]:
g = game_info[1]
# snake_head = game_info[1]['snake_head']
food = game_info[1]['food']
# speed_x = game_info[1]['ball_speed'][0]#game_info[2]['ball'][0] - game_info[1]['ball'][0]
# speed_y = game_info[1]['ball_speed'][1]#game_info[1]['ball'][1] - game_info[2]['ball'][1]+
# blocker = game_info[1]["blocker"][0]
# bricks = len(game_info[1]['bricks'])
# if speed_x > 0:
#     if speed_y > 0:
#         Direction = 0
#     else:
#         Direction = 1
# else:
#     if speed_y > 0:
#         Direction = 2
#     else:
#         Direction = 3
# Direction = Direction * 50
a = [tuple(g['snake_head']),tuple(g['food'])]
print("a= ", a)
feature = np.array([a])#,speed_x,speed_y],bricks)
print(feature)
print(feature.shape)

print(game_command[1])
game_command[1] = 0

a=  [(50, 40), (200, 150)]
[[[ 50  40]
  [200 150]]]
(1, 2, 2)
RIGHT


In [10]:
for i in range(2, len(game_info) - 1):##從這開始改
    #print(i)
    g = game_info[i]
#     speed_x = game_info[i]['ball_speed'][0]
#     speed_y = game_info[i]['ball_speed'][1]
#     if speed_x > 0:
#         if speed_y > 0:
#             Direction = 0
#         else:
#             Direction = 1
#     else:
#         if speed_y > 0:
#             Direction = 2
#         else:
#             Direction = 3
#     Direction = Direction * 50
#     blocker = game_info[i]['blocker'][0]
    a = [tuple(g['snake_head']),tuple(g['food'])]
    feature = np.vstack((feature, [a]))#,speed_x,speed_y])),bricks
    if game_command[i] == "UP": game_command[i] = 0
    elif game_command[i] == "RIGHT": game_command[i] = 1
    elif game_command[i] == "LEFT": game_command[i] = 2
    else: game_command[i] = 3
    
answer = np.array(game_command[1:-1])

print(feature)
print(feature.shape)
print(answer)
print(answer.shape)

[[[ 50  40]
  [200 150]]

 [[ 60  40]
  [200 150]]

 [[ 70  40]
  [200 150]]

 ...

 [[260  50]
  [270  50]]

 [[270  50]
  [220 130]]

 [[280  50]
  [220 130]]]
(656992, 2, 2)
[0 1 1 ... 1 1 1]
(656992,)


### KNN官方文件
https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html
### 交叉驗證
https://chih-sheng-huang821.medium.com/%E4%BA%A4%E5%8F%89%E9%A9%97%E8%AD%89-cross-validation-cv-3b2c714b18db

In [17]:
from sklearn.ensemble import RandomForestClassifier
#資料劃分
x_train, x_test, y_train, y_test = train_test_split(feature, answer, test_size=0.3, random_state=1)
nsamples, nx, ny = x_train.shape
x_train = x_train.reshape((nsamples,nx*ny))
nsamples, nx, ny = x_test.shape
x_test = x_test.reshape((nsamples,nx*ny))
model = RandomForestClassifier(n_estimators = 5, max_depth = 500, random_state = 0)
model.fit(x_train,y_train)
print(model.score(x_test, y_test))

#參數區間
# param_grid = {'n_neighbors':[1, 2, 3, 4, 5]}

# ## add
# nsamples, nx, ny = x_train.shape
# x_train = x_train.reshape((nsamples,nx*ny))
# nsamples, nx, ny = x_test.shape
# x_test = x_test.reshape((nsamples,nx*ny))
# ##add above
# #交叉驗證 
# cv = StratifiedShuffleSplit(n_splits=6, test_size=0.3, random_state=12)
# grid = GridSearchCV(KNeighborsClassifier(n_neighbors=5),param_grid, cv=cv, verbose=10, n_jobs=-1) #n_jobs為平行運算的數量
# grid.fit(x_train, y_train)
# grid_predictions = grid.predict(x_test)

#儲存
file = open('model.pickle', 'wb')
pickle.dump(model, file)
file.close()

0.9972856142629555


### f1-score
https://medium.com/nlp-tsupei/precision-recall-f1-score%E7%B0%A1%E5%96%AE%E4%BB%8B%E7%B4%B9-f87baa82a47

In [ ]:
#最佳參數
print(grid.best_params_)
#預測結果
#print(grid_predictions)
#混淆矩陣
print(confusion_matrix(y_test, grid_predictions))
#分類結果
print(classification_report(y_test, grid_predictions))

### 執行遊戲
python MLGame.py -f 100 -i model_DJ.py arkanoid NORMAL 3